INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_GUEST');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_SUPER_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_MAIN_ADMIN');
